themes:
  tomorrow_night: 'Tomorrow Night'
  ambiance: 'Ambiance'
  chaos: 'Chaos'
  chrome: 'Chrome'
  clouds: 'Clouds'
  clouds_midnight: 'Clouds Midnight'
  cobalt: 'Cobalt'
  crimson_editor: 'Crimson Editor'
  dawn: 'Dawn'
  dreamweaver: 'Dreamweaver'
  eclipse: 'Eclipse'
  github: 'GitHub'
  idle_fingers: 'idle Fingers'
  katzenmilch: 'KatzenMilch'
  kr_theme: 'krTheme'
  kuroir: 'Kuroir'
  merbivore: 'Merbivore'
  merbivore_soft: 'Merbivore Soft'
  mono_industrial: 'Mono Industrial'
  monokai: 'Monokai'
  pastel_on_dark: 'Pastel on dark'
  solarized_dark: 'Solarized Dark'
  solarized_light: 'Solarized Light'
  terminal: 'Terminal'
  textmate: 'TextMate'
  tomorrow: 'Tomorrow'
  tomorrow_night_blue: 'Tomorrow Night Blue'
  tomorrow_night_bright: 'Tomorrow Night Bright'
  tomorrow_night_eighties: 'Tomorrow Night 80s'
  twilight: 'Twilight'
  vibrant_ink: 'Vibrant Ink'
  xcode: 'XCode'

indents:
  '2': '2 spaces'
  '4': '4 spaces'
  '8': '8 spaces'
  tab: 'Tabs'

languages:
  ruby: 'Ruby'
  c: 'C'
  cpp: 'C++'
  csharp: 'C#'
  golang: 'Go'
  java: 'Java'
  php: 'PHP'
  python2: 'Python 2'
  python3: 'Python 3'
  node: 'Node.js'
  rust: 'Rust'

keyboards:
  ace: 'Ace'
  emacs: 'Emacs'
  'vim': 'Vim'
