development:
  sorcery_github_callback_url: http://192.168.59.103:3000/oauth/callback?provider=github
  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>

  secret_key_base: 04d66f2359c4af72e33380dedd0c047a1a5da69cf03a43117753cf1d236e266a1ba6c06c849201c0908ce923e8bfce51b2058a4dfc632bf96beb7ec85738c4bd

test:
  secret_key_base: d544af875bb0208152a7ffe723c3aed8c811ea8274cfd71afc96e33c0071e736a5f07dc896de5fd4032b3639cf29174c9c28f0d9c8d496f7e7edbff50a534642

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  sorcery_github_callback_url: <%= ENV["SORCERY_GITHUB_CALLBACK_URL"] %>
  sorcery_github_key: <%= ENV["SORCERY_GITHUB_KEY"] %>
  sorcery_github_secret: <%= ENV["SORCERY_GITHUB_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
